// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWatchState.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWatchState.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyWatchState.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.UserVideoProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<DateTimeOffset?>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_watched_at");

                    b.Property<double>("ProgressSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_user_video_progress");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_video_progress_user_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_user_video_progress_video_id");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_video_progress_user_id_video_id");

                    b.ToTable("user_video_progress", (string)null);
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.Video", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformVideoId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("platform_video_id");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_url");

                    b.HasIndex("Platform", "PlatformVideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_platform_platform_video_id")
                        .HasFilter("platform_video_id IS NOT NULL");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.WatchSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<double?>("ProgressAtEnd")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_at_end");

                    b.Property<double>("ProgressAtStart")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_at_start");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_watch_sessions");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_watch_sessions_started_at");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_watch_sessions_video_id");

                    b.HasIndex("UserId", "VideoId")
                        .HasDatabaseName("ix_watch_sessions_user_id_video_id");

                    b.ToTable("watch_sessions", (string)null);
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.UserVideoProgress", b =>
                {
                    b.HasOne("MyWatchState.Domain.Entities.User", "User")
                        .WithMany("VideoProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_video_progress_users_user_id");

                    b.HasOne("MyWatchState.Domain.Entities.Video", "Video")
                        .WithMany("UserProgress")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_video_progress_videos_video_id");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.WatchSession", b =>
                {
                    b.HasOne("MyWatchState.Domain.Entities.User", "User")
                        .WithMany("WatchSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_sessions_users_user_id");

                    b.HasOne("MyWatchState.Domain.Entities.Video", "Video")
                        .WithMany("WatchSessions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_sessions_videos_video_id");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.User", b =>
                {
                    b.Navigation("VideoProgress");

                    b.Navigation("WatchSessions");
                });

            modelBuilder.Entity("MyWatchState.Domain.Entities.Video", b =>
                {
                    b.Navigation("UserProgress");

                    b.Navigation("WatchSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
